version: 1.0.{build}
image:
  - Visual Studio 2019
  - ubuntu1804
  - macos
  - macos-mojave
environment:
  NO_EXTERNAL_TESTS: 1
  matrix:
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310
  - TOXENV: py311

install:
- cmd: pip install tox
build: off
test_script:
- cmd: tox
